### ISSUE TITLE
confused about which env to use : mbo or design-baselines?

### ISSUE THREAD

**Issue by SourinDeyUW** [brandontrabucco/design-bench#17]
At the beginning of readme the instructions are given for installing mbo but later instructions are for design-benchlines. 
After I just install mbo, I could not run the **Reproducing Baseline Performance** codes. I could run (facing issues though) the codes after I install design-benchlines . My question is why should I install mbo if I am not using it at all.

**Comment by brandontrabucco** [comment]
Hi [SourinDeyUW](https://github.com/SourinDeyUW),

Thanks for your interest in our code!

`design-baselines` is a separate package that contains reference implementations of baselines. This needs to be installed if you want to use our baseline algorithms for benchmarking purposes.

```
git clone https://github.com/brandontrabucco/design-baselines
conda env create -f design-baselines/environment.yml
conda activate design-baselines
```

If you need these, then the `mbo` environment is not required. Otherwise, if you don't need to use the baselines, then you only need to create the base `mbo` environment (which has fewer packages installed than `design-baselines`).

Also, `mbo` is just a conda environment name we chose for illustration purposes, feel free to choose your own!
